-- =====================================================
-- CSI Admin Portal - Database Setup
-- Run this ONCE in the Supabase SQL Editor
-- =====================================================

-- 1. Admin allowlist -----------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
  email TEXT PRIMARY KEY,
  added_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- !!! IMPORTANT: add YOURSELF as the first admin !!!
INSERT INTO admin_users (email, added_by)
VALUES ('studyonaffan@gmail.com', 'initial-setup')
ON CONFLICT (email) DO NOTHING;

-- 2. Magazines ------------------------------------------
CREATE TABLE IF NOT EXISTS magazines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  cover_url TEXT,
  pdf_url TEXT NOT NULL,
  pages INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Resources ------------------------------------------
CREATE TABLE IF NOT EXISTS resources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  pdf_url TEXT,
  link_url TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Team table upgrades --------------------------------
ALTER TABLE csi_team ADD COLUMN IF NOT EXISTS portfolio TEXT;
ALTER TABLE csi_team ADD COLUMN IF NOT EXISTS gb_position TEXT;
ALTER TABLE csi_team ADD COLUMN IF NOT EXISTS team_year TEXT DEFAULT '2025-26';
CREATE INDEX IF NOT EXISTS idx_csi_team_year ON csi_team(team_year);
CREATE INDEX IF NOT EXISTS idx_csi_team_active ON csi_team(is_active);

-- 5. Storage bucket for uploads --------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('media', 'media', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Public read for the media bucket
DROP POLICY IF EXISTS "media public read" ON storage.objects;
CREATE POLICY "media public read" ON storage.objects
  FOR SELECT USING (bucket_id = 'media');

-- 6. Row Level Security ----------------------------------
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE magazines ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;

-- Public read for site content (writes go through service role, which bypasses RLS)
DROP POLICY IF EXISTS "magazines public read" ON magazines;
CREATE POLICY "magazines public read" ON magazines FOR SELECT USING (TRUE);
DROP POLICY IF EXISTS "resources public read" ON resources;
CREATE POLICY "resources public read" ON resources FOR SELECT USING (TRUE);

-- =====================================================
-- 7. SEED DATA (run once; skip this section if re-running)
-- =====================================================

-- Clear existing team rows to avoid duplicates when seeding
-- (comment out the next line if you already have team data you want to keep)
DELETE FROM csi_team;

INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (1,'Muhammad Affan Asif','Chief Coordinator','gb','/team/affan.png','https://www.linkedin.com/in/affan-asif-383451178/','https://github.com/Affan-Asif','160422733145@mjcollege.ac.in',NULL,'Chief Coordinator','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (2,'Mohammad Touseef Banu','Chief Coordinator','gb','/team/tauseef.jpg',NULL,NULL,NULL,NULL,'Chief Coordinator','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (3,'Mohammed Abdullah Shareef','Chief Coordinator','gb','/team/abdullahshareef.jpg',NULL,NULL,NULL,NULL,'Chief Coordinator','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (4,'Mohammed Abdul Haseeb Khan','Associate CC','gb','/team/haseeb.jpg',NULL,NULL,NULL,NULL,'Associate CC','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (5,'Nusrah Khan','Associate CC','gb','/team/nusrah.jpg',NULL,NULL,NULL,NULL,'Associate CC','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (6,'Mir Danish Ahmed','Associate CC','gb','/team/danish.jpeg',NULL,NULL,NULL,NULL,'Associate CC','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (7,'Mehvish Waheed','Tech Captain','gb','/team/mehvish.jpg','mehvish-waheed-88b9b5277','https://github.com/Mehvishh25','mehvish.waheed.25@gmail.com','Tech','Tech Captain','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (8,'Meer Aymaan Ali','Tech Captain','gb','/team/meeraymanali.jpeg','https://www.linkedin.com/in/meer-aymaan-ali-01554030b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app','https://github.com/meer3305','meeraymaanali@gmail.com','Tech','Tech Captain','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (9,'Ameena Begum','Tech Captain','gb','/team/ameena.jpg','https://www.linkedin.com/in/ameena-begum-3a8526315?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/ameena-begum1','ameenahsyed1@gmail.com','Tech','Tech Captain','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (10,'Abdullah Yar Khan','Chief Representative','gb','/team/abdullahyarkhan.jpg',NULL,NULL,'placeholder-abdullahyar@example.com',NULL,'Chief Representative','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (11,'Syeda Noor Fatima','Chief Representative','gb','/team/noorfatime.jpeg','syedanoorfatima','https://github.com/itsnoorfatima','synoorf@gmail.com','Design','Chief Representative','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (12,'Mohammadi Fatima','General Secretary','gb','/team/mohammadi.png',NULL,'https://github.com/MohammadiFatima','mohammadifatima1224@gmail.com','Editorial','General Secretary','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (13,'Iqra Fatima','Deputy GS','gb','/team/iqra.jpg',NULL,'https://github.com/iqrfatima',NULL,NULL,'Deputy GS','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (14,'Mohammed Azeem Uddin Siddiqui','Treasurer','gb','/team/azeem.jpeg','https://www.linkedin.com/in/azeem-siddiqui-036514254?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app','https://github.com/Azeemsiddiquiii','160422733167@mjcollege.ac.in','Media','Treasurer','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (15,'Syed Imran','Hackathons and external','gb','/team/imran.jpeg',NULL,NULL,NULL,NULL,'Hackathons and external','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (16,'Syed Fauzaan','Communication & Collaboration','gb','/team/fauzaan.jpeg',NULL,NULL,NULL,NULL,'Communication & Collaboration','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (17,'Salman Mohammed Arif','Advisor of Sponsorship & PR','gb','/team/salman.jpeg','https://www.linkedin.com/in/salman-mohammed-arif-387187284?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app','https://github.com/BlackCap07','Salmanmohammedarif@gmail.com','Media','Advisor of Sponsorship & PR','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (18,'BATER IBRAHIM KHAN','Advisor of Student Affairs','gb','/team/ibrahim.jpeg','https://www.linkedin.com/in/ibrahim-khan-9a831a29b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app','https://github.com/IbrahimKhan222','160423733035@mjcollege.ac.in','Marketing','Advisor of Student Affairs','2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (1,'Syed Mukhtar','Tech Core','core',NULL,NULL,'https://GitHub.com/SyedMukhtar11','160424733011@mjcollege.ac.in','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (2,'Mohammed Abdul Majeed','Tech Core','core','https://drive.google.com/thumbnail?id=1P9Sg5Bzb-_688302TqEcOSaju3jOlngB','https://www.linkedin.com/in/mohammed-abdul-majeed-647093344?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app','https://github.com/mabdulmajeed113','mabdulmajeed113@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (3,'Mohammed Saad','Tech Core','core','https://drive.google.com/thumbnail?id=1CURO09da4gGaXLI4CxeZYUVr4vvE2w-B','https://www.linkedin.com/in/mohammed-saad-b41b20308','https://github.com/183108142','iamsaad365@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (4,'Mohammad zainuddin','Tech Core','core',NULL,NULL,NULL,'placeholder-zainuddin@example.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (5,'Ali Mohammad Abedi Syed','Tech Core','core','https://drive.google.com/thumbnail?id=1VKVFk4w2EvkhN9p6WCp9p2i5xw8I2-1C','https://www.linkedin.com/in/ali-mohammed-abedi-syed-630491305','https://github.com/Mamba343','ssyedali346@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (6,'Syed Husamuddin Haji','Tech Core','core','https://drive.google.com/thumbnail?id=1zEtmSjyk_MBW7Uhl3aI8GtnORtLWGrdp',NULL,'https://github.com/husam025','husam25@proton.me','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (7,'Mohd Mubashir Ahmed','Tech Core','core','https://drive.google.com/thumbnail?id=1jzhscL549sWwUGBZSYNuz9cEJfKM3Yyr',NULL,'https://github.com/MohdMubashir29','mohdmubashir2909@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (8,'Ruqayyah Zaheeruddin','Tech Core','core',NULL,NULL,NULL,'placeholder-ruqayyah@example.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (9,'Ahmed Nehan Razi','Tech Core','core',NULL,NULL,NULL,'nehanmjcet@gmai.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (10,'Affaaf Ahmed','Tech Core','core','https://drive.google.com/thumbnail?id=17NM2iYt42KNPPhe3nloiKHv-bLhSAWgq','https://www.linkedin.com/in/affaaf-ahmed','https://github.com/Affaaf-Ahmed','160424733012@mjcollege.ac.in','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (11,'Linra Khan','Tech Core','core',NULL,'https://www.linkedin.com/in/linra-khan-785585331','https://github.com/Linraa24','160424733426@mjcollege.ac.in','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (12,'Nabeel uddin','Tech Core','core',NULL,'https://linkedin.com/in/mohammed-nabeel-uddin-2ab19b391','https://github.com/nabeel-lab?tab=following','mhnu.6180@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (13,'Zaina Tahniyath','Tech Core','core','https://drive.google.com/thumbnail?id=14RYJ5GVukJ5MB5lylfPnnEONwOXtgZPr','https://www.linkedin.com/in/zaina-tahniyath-490701336?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/ZAINA11749','Zainatahniyath7@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (14,'Abdul Dareem Khan','Tech Core','core','https://drive.google.com/thumbnail?id=1dm5Zdx6Ssf_TkYyldmSkBJJspHy04cH2','https://www.linkedin.com/in/abdul-dareem-khan-711506397?utm_source=share_via&utm_content=profile&utm_medium=member_ios','https://github.com/Dareem380','160424733380@mjcollege.ac.in','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (15,'Gulam Mustafa Madni','Tech Core','core',NULL,NULL,NULL,'160424733417@mjcollege.ac.in','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (16,'Sama Nooreen','Web Core','core',NULL,NULL,NULL,'placeholder-sama@example.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (17,'Areebha Tazeem','Web Core','core','https://drive.google.com/thumbnail?id=1xgIRGu5dS32t3rfvpLr3ckdxZW1sYaM9','https://linkedin.com/in/areebha-tazeem-b221a6340','https://github.com/235859911','jafarareebha@gmail.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (18,'Aaryan Khoja','Web Core','core','https://drive.google.com/thumbnail?id=1ONBbnXFIXaTgjYwBmmrunPMucgbLbF5L','https://www.linkedin.com/in/aaryan-khoja','https://github.com/AaryanKhoja','008aaryankhoja@gmail.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (19,'Mohammed Humam Tausif','Web Core','core',NULL,NULL,NULL,'placeholder-humam@example.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (20,'Mohammed Muzammil Ahmed','Web Core','core',NULL,NULL,NULL,'placeholder-muzammil@example.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (21,'Syed Jalaluddin','Web Core','core',NULL,'https://www.linkedin.com/in/syed-jalaluddin-374797344','https://github.com/syedjalal-503','syedjalaluddin48@gmail.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (22,'Mohammed Talha','Web Core','core',NULL,NULL,NULL,'placeholder-talha@example.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (23,'Mirza Zohair Ali Baig','Web Core','core',NULL,NULL,NULL,'placeholder-zohair@example.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (24,'Mohammed Zakeer','Web Core','core','https://drive.google.com/thumbnail?id=1A9IYYtR5tmeVyqe-qLlLL9bVpNlRVesA','https://www.linkedin.com/in/mohammed-zakeer-b7ba25342?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/zak104','zak406999@gmail.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (25,'Aisha Gowher','Web Core','core','https://drive.google.com/thumbnail?id=12_ScsJGcCOAXM9Ic8IvGiuRk9gIMr2FI','https://www.linkedin.com/in/aisha-gowher-mir-234940274','https://github.com/aisha-mir790','aishagowhermir@gmail.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (26,'Tooba Gowher','Web Core','core',NULL,NULL,NULL,'placeholder-tooba@example.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (27,'Mohammed Talha','Web Core','core',NULL,NULL,NULL,'placeholder-talha2@example.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (28,'Syed Ali Mahmood adeen','Web Core','core',NULL,NULL,NULL,'placeholder-adeen@example.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (29,'Syeda Ayesha','HR Core','core','https://drive.google.com/thumbnail?id=18eXKuOI9PiWIbjKLmwSF076zwEQgIbcR',NULL,'https://github.com/SyedaAyeshaa111','syedaayesha7496@gmail.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (30,'Ayesha Mirza','HR Core','core',NULL,NULL,NULL,'placeholder-ayesham@example.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (31,'Mohammed ismayeel','HR Core','core','https://drive.google.com/thumbnail?id=1G4qrmWu2N-cfqJZoC3T62GxeK4mpNt-g',NULL,NULL,'Ismayeel.07@gmail.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (32,'Mohammed Zaid Farooqui','HR Core','core',NULL,NULL,NULL,'placeholder-zaid@example.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (33,'Fareeha Manal','HR Core','core','https://drive.google.com/thumbnail?id=1FI9n0sOga-o_5kNi6X0ofUN6GpdSzTZT',NULL,'https://github.com/Fareeha-manal074','manalfareeha@gmail.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (34,'Zunaira Khanam','HR Core','core',NULL,NULL,NULL,'placeholder-zunaira@example.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (35,'Ahamadi Hareem','HR Core','core',NULL,NULL,NULL,'placeholder-hareem@example.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (36,'Mohammed Abdul Aashir','Events Core','core','/team/core/aashir-event.png',NULL,NULL,'placeholder-waheed@example.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (37,'Amaan Khan','Events Core','core',NULL,NULL,NULL,'placeholder-amaan@example.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (38,'Huda fathima','Events Core','core',NULL,'https://www.linkedin.com/in/huda-fathima-700422326',NULL,'hudafathima1414@gmail.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (39,'Mohammed Zain Shareef','Events Core','core',NULL,NULL,NULL,'placeholder-zain@example.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (40,'Safia Saif','Events Core','core','https://drive.google.com/thumbnail?id=15_SA_IV9v81PzDoYsWzkJhBTVJOLfksy','https://www.linkedin.com/in/safia-saif-55b2b5391','https://github.com/saifsafia082-cyber','saifsafia082@gmail.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (41,'Mohammed Jawad Khan','Events Core','core',NULL,NULL,NULL,'placeholder-jawad@example.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (42,'Syed Rizwan Ahmed','Events Core','core',NULL,NULL,'https://github.com/Syedrizwan78823-rn','Syedrizwan78823@gmail.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (43,'Syeda Hafsa Saherun','Design Core','core',NULL,'https://www.linkedin.com/in/syeda-hafsa-saherun-880547388','https://github.com/syedasaherun-byte','syedasaherun@gmail.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (44,'Mohammed Saad','Design Core','core','https://drive.google.com/thumbnail?id=17rdRUpvXIN6lF0hwUgN6CRiIDKkhNgFg','https://www.linkedin.com/in/mohammed-saad-794493382?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/OGBrowny','mohammedsaad159op@gmail.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (45,'Syed Mohammed Rayan','Design Core','core','https://drive.google.com/thumbnail?id=1APnpcwztFKZnJ6t2QIt0991nefAyWmkK',NULL,'https://github.com/syedmohammedrayan','syedmohammedrayan2007@gmail.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (46,'Mariyam Fatima','Design Core','core',NULL,NULL,NULL,'placeholder-mariyam@example.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (47,'Bibi Almas','Design Core','core',NULL,'https://www.linkedin.com/in/bibialmas7777','https://github.com/Almas1910','almasbibi888@gmail.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (48,'Manaal Fatima','Design Core','core',NULL,NULL,NULL,'placeholder-manaal@example.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (49,'Mohammed Anzar Siddiqui','Design Core','core','https://drive.google.com/thumbnail?id=1ybr2lITzyzSJCZbcBjvgtiRP5mo8JmHY',NULL,'https://github.com/anzar2629','anzar6673@gmail.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (50,'Nuha Naser','Design Core','core',NULL,NULL,NULL,'placeholder-nuha@example.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (51,'Nabiha Fatima','Editorial Core','core',NULL,NULL,NULL,'placeholder-nabiha@example.com','Editorial',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (52,'Mohammed Umar Ali Azam','Editorial Core','core',NULL,NULL,NULL,'placeholder-umar@example.com','Editorial',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (53,'Gazala Jabeen Hafsa','Editorial Core','core',NULL,NULL,NULL,'placeholder-gazala@example.com','Editorial',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (54,'Sofia Fatima','Editorial Core','core',NULL,NULL,NULL,'placeholder-sofia@example.com','Editorial',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (55,'Syed Rozan Ali','Editorial Core','core',NULL,NULL,NULL,'placeholder-rozan@example.com','Editorial',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (56,'Mohammed Sujathullah Amaan','Media Core','core','https://drive.google.com/thumbnail?id=12OV8gh6leDhG8YvnzUPXyPAZeZU7cGD2','https://www.linkedin.com/in/mohammed-sujathullah-amaan-0b926a307?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/Amaan-says','sujathullahsajji@gmail.com','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (57,'Asma Fatima Khan','Media Core','core','/team/core/asma-media.jpg',NULL,'https://github.com/AsmaFatimaKhan','160424733427@mjcollege.ac.in','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (58,'Mohammed Shayaan Baig','Media Core','core','https://drive.google.com/thumbnail?id=1QLDrxn-9zoxp6-itKRC8QaTqq8Wb3qxX',NULL,'https://github.com/160424733055-design','160424733055@mjcollege.ac.in','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (59,'Mohammed Zayan','Media Core','core',NULL,NULL,NULL,'placeholder-zayan@example.com','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (60,'Mohammed Khan( Muqeem)','Media Core','core',NULL,NULL,NULL,'placeholder-muqeem@example.com','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (61,'Hafsa Batool','Media Core','core',NULL,NULL,NULL,'placeholder-hafsa@example.com','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (62,'Jazlain Uddin','Marketing Core','core',NULL,NULL,NULL,'placeholder-jazlain@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (63,'Sheeza Ahmed','Marketing Core','core',NULL,NULL,NULL,'placeholder-sheeza@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (64,'Ashaz Sulaiman Khan','Marketing Core','core',NULL,NULL,NULL,'placeholder-ashaz@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (65,'Mohammed Ibrahim','Marketing Core','core',NULL,NULL,NULL,'placeholder-ibrahim@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (66,'Mahreen Fatima','Marketing Core','core',NULL,NULL,NULL,'placeholder-mahreen@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (67,'Shezan Ali','Marketing Core','core',NULL,NULL,NULL,'placeholder-shezan@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (68,'Mohammed Saeed Ali','Marketing Core','core',NULL,NULL,NULL,'placeholder-saeed@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (69,'Zaid Mohiuddin','Operations Core','core','https://drive.google.com/thumbnail?id=1xAJPQW7aZV-ZMCZv1PesX8HmqH1PqR_F','https://www.linkedin.com/in/zaid-mohiuddin-4364b9376','https://github.com/zaidmohiuddin1533-bit','zaidmohiuddin1533@gmail.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (70,'Mohammed Omer Khan','Operations Core','core',NULL,NULL,NULL,'mdomerkhan752@gmail.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (71,'Mohammed Hamzah Kamar','Operations Core','core',NULL,NULL,NULL,'placeholder-hamzah@example.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (72,'Shaik Abdus Salam','Operations Core','core','https://drive.google.com/thumbnail?id=1qBqh8aOZgKU4mJsVOq-yS6k8vr7XSH-2','https://www.linkedin.com/in/abdus-salam-069a41313','https://github.com/abdus-code','as2000.fire@gmail.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (73,'Syed Ahmed Mujhtaba','Operations Core','core','https://drive.google.com/thumbnail?id=1Q2DNAW1NGuQ4WjsF0GDEO_iRwnKOKZG7','https://www.linkedin.com/in/ahmed-mujhtaba/','https://github.com/Mujtabaa187','syedahmedmujtaba06@gmail.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (74,'Abdul Haq Hamdan','Operations Core','core',NULL,NULL,NULL,'placeholder-hamdan@example.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (75,'Mohammed Farhan Uddin','Operations Core','core','https://drive.google.com/thumbnail?id=1GEEt9BLZP8ry5aY_EYV8nUwzzzQpbW8V',NULL,NULL,'farhanuddin7530@gmail.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (1,'Md Feroz Ahmed','Tech Head','execom',NULL,'https://www.linkedin.com/in/md-feroz-ahmed-2a3633375','https://github.com/phero20','mdferozahmed27156@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (2,'Irfan Sirkar','Tech Head','execom','https://drive.google.com/thumbnail?id=1GkybJrfVgOv97N2k_4zamoY8vlunS9K3','https://www.linkedin.com/in/irfan-sirkar-2124932a0?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app','https://github.com/irfansirkar','Sirkarks@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (3,'Rabia Mansoor','Tech Head','execom','https://drive.google.com/thumbnail?id=1BSp5_2UJoSx9N7Gc-VqcOG1t9UQrjYsp','https://www.linkedin.com/in/rabiamansoor','https://github.com/Rabia4M','rmansoor4002@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (4,'Mohammed Imran Ahmed Yousuf','Tech Head','execom',NULL,'https://www.linkedin.com/in/mohammedimranahmedyousuf','https://github.com/1mranAhmed','placeholder-imran@example.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (5,'Abdullah Hafeez','Tech Associate Head','execom','https://drive.google.com/thumbnail?id=18onRLfae1aRvtxvZuM0rrxOZvqzLfmq-','https://www.linkedin.com/in/abdullah-hafeez-qureshi-16a25a142?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/AbdullahHafeez2004','abdullahhafeez712@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (6,'Daaniyah Khan','Tech Associate Head','execom',NULL,NULL,NULL,'placeholder-dervesh@example.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (7,'Mir Reza Ali Khan','Tech Associate Head','execom','https://drive.google.com/thumbnail?id=1vJnoexmeM4OAtvuXYz9dFf2VzykH8f9n','https://www.linkedin.com/in/mir-reza-ali-khan','https://github.com/MirRezaAliKhan','mirrezaalikhan.in@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (8,'Md Atif Ali Khan','Tech Associate Head','execom',NULL,NULL,NULL,'placeholder-ali@example.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (9,'Mohd Haseeb Uddin','Tech Associate Head','execom','https://drive.google.com/thumbnail?id=1CS700DNCq0tEbQItx5CBThphMKbqp-jy',NULL,'https://github.com/MohdHaseebUddin786','mohdhaseebuddin814@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (10,'Abdul Mateen Khan','Web Head','execom','https://drive.google.com/thumbnail?id=1n0mS2us7QN_w-AdlVUJ-LFpS6Xkt4tfj','https://www.linkedin.com/in/abdul-mateen-khan-85163829b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/05mateenkhan','05mateenkhan@gmail.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (11,'Shaik Mohammed Ismail','Web Head','execom','https://drive.google.com/thumbnail?id=1k6pQ_80HHgxvuGYeGmwLb6RNNpYSqUNZ','https://www.linkedin.com/in/shaik-mohammed-ismail/','https://github.com/shaik-ismail-27','ismail.email.at@gmail.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (12,'Iram Fatima','HR Head','execom',NULL,NULL,NULL,'placeholder-iram@example.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (13,'Farhan Uddin','HR Associate Head','execom','https://drive.google.com/thumbnail?id=11aC9x3-_sAgTj0_R9NR_jA0cD3junTz4','https://www.linkedin.com/in/farhanuddin0721','https://github.com/FarhanUddin0721','farhaanu851@gmail.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (14,'Mohammed Omer Farooq','HR Associate Head','execom',NULL,NULL,NULL,'placeholder-omer@example.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (15,'Mohammed Zaheer Khan','Events Head','execom',NULL,NULL,NULL,'placeholder-najeeb@example.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (16,'Hamza Mohammed Jeelani','Events Head','execom',NULL,NULL,NULL,'placeholder-hamza@example.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (17,'Sariah Fatima','Design Head','execom',NULL,NULL,NULL,'placeholder-saniah@example.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (18,'Asma Begum','Design Head','execom','https://drive.google.com/thumbnail?id=1QBKHUACLSnzJscIoSnWFG5Jemk2AmB9i','https://www.linkedin.com/in/asma-begum-7862702a4','https://github.com/Asma6304','160423733070@mjcollege.ac.in','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (19,'Syed Rehan Pasha','Design Head','execom','https://drive.google.com/thumbnail?id=1O6vMX6sZSeusVwq6gmtsfWscSh0NhiSm',NULL,'https://github.com/Syedrehan9824','rehan848179@gmail.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (20,'Syeda Kaneez Fatima','Design Associate Head','execom','https://drive.google.com/thumbnail?id=1u3oIkYT5tk26c1KEVtaAaQrepgcGmzgN',NULL,'https://github.com/Syeda-kaneez','syedakaneez06@gmail.com','Design',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (21,'Mohammed Fawaz Malik','Editorial Head','execom','https://drive.google.com/thumbnail?id=1q4t6SLDZZAhrQOroUBw-ESTYKOFqaEIx','https://www.linkedin.com/in/mohammed-fawaz-malik-922388310?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/fxwyz08','fxwyz08@gmail.com','Editorial',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (22,'Sana Sayeed','Editorial Associate Head','execom',NULL,NULL,NULL,'placeholder-sana@example.com','Editorial',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (23,'Syed Mohammed Moinuddin Hussaini','Editorial Associate Head','execom','https://drive.google.com/thumbnail?id=1ZWh4uRPZ6F6jntW_-RwT2nniHjFCNRI9','https://www.linkedin.com/in/syed-mohammed-moinuddin-hussaini-572791332?utm_source=share_via&utm_content=profile&utm_medium=member_android','https://github.com/MR-AWESOME99','syedmoinuddin.smmh@gmail.com','Editorial',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (24,'Syeda Mirza','Media Head','execom',NULL,NULL,NULL,'placeholder-ateeb@example.com','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (25,'Faiza Mahveen','Media Associate Head','execom',NULL,'https://www.linkedin.com/in/faiza-mahveen-82b389308?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app','https://github.com/famahi04','faiza.mahveen2206@gmail.com','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (26,'Shujath ali khan','Media Associate Head','execom','https://drive.google.com/thumbnail?id=18AaWH1G8SsTxZTl7A7F-63wVs7kDLFBy','https://www.linkedin.com/in/shujath-ali-khan-53b42738a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/shujaatkhan20','Kshujath16@gmail.com','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (27,'Raisa Ahmed','Media Associate Head','execom','https://drive.google.com/thumbnail?id=1TItZAcAxk0AjypnXci8cnXRemSs6goZ8',NULL,NULL,'raisa9885771138@gmail.com','Media',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (28,'Mudassiruddin Ahmed','Marketing Head','execom',NULL,NULL,NULL,'placeholder-mudassiruddin@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (29,'Syeda Shahakaar','Marketing Associate Head','execom','https://drive.google.com/thumbnail?id=1wrivDffFiZ07wACA47YwgGadqjmYyOby','https://www.linkedin.com/in/syeda-shahakaar-bb5885376',NULL,'syedashahakaar8@gmail.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (30,'Mohammed Ayaz Khan','Operations Head','execom',NULL,NULL,NULL,'placeholder-ayaz@example.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (31,'Zaina Bilquis','Tech Associate Head','execom','https://drive.google.com/thumbnail?id=1gTT63lHODdOLd5uyr5INW_Pg0t32wl9Y','https://www.linkedin.com/in/zaina-bilquis-208586331','https://github.com/Zaina-B06','zainabilquis06@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (32,'Syed Unais Panjathan','Tech Associate Head','execom','https://drive.google.com/thumbnail?id=1tjVEx0-c0uFeOtISaFnwegMmKafb_Ewb','https://www.linkedin.com/in/syed-unais-panjathan?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/syedunaisp','syedunais516@gmail.com','Tech',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (33,'Mohammed Osman','Web Associate Head','execom','https://drive.google.com/thumbnail?id=1DGIGMziwwRSaRWGaNQ6dq_K2i55oxZwn','https://www.linkedin.com/in/mohammed-osman-b7b656381?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','httpsB://www.github.com/thecodinganvil','muhammedosmanraheemkhan@gmail.com','Web',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (34,'Hasifa Ammara','HR Head','execom',NULL,'https://www.linkedin.com/in/hasifa-ammara-3b9a842a0?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/Tiu8g84588g83r8y8v8r8y8f8e8t88fr9/portfolio-basic','Ammarahasifa@gmail.com','HR',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (35,'Mohammed Abbu Bakar','Events Associate Head','execom','https://drive.google.com/thumbnail?id=13k4bBLXc9IxL8Aus5EkyOViN0Fy9vqS2',NULL,'https://github.com/abbubakar07','mohdabbubakar05@gmail.com','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (36,'Juveria Zaheer','Events Associate Head','execom',NULL,NULL,'https://github.com/jaarso0','160423733125@mjcollege.ac.in','Events',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (37,'Syed Abu Bakr Hussain','Marketing Head','execom',NULL,NULL,NULL,'placeholder-abubakr@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (38,'Mohammed Abdul Saboor','Marketing Associate Head','execom',NULL,NULL,NULL,'placeholder-omarsaboor@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (39,'Omar Alamgir','Marketing Associate Head','execom','https://drive.google.com/thumbnail?id=1mmvKlns0WE22RweZDySlhvbPB2tu2xuJ','https://www.linkedin.com/in/omer-alam-49343531a','https://github.com/aalamomar88-star','aalamomar88@gmail.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (40,'Abdul qawi khan','Marketing Associate Head','execom',NULL,NULL,NULL,'placeholder-qavi@example.com','Marketing',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (41,'Mohammed Ilyas Ahmed','Operations Head','execom','https://drive.google.com/thumbnail?id=1Ii8S4PcJ3rWg-E7X0gdoOgYBaB4BLAT8','https://www.linkedin.com/in/mohammed-ilyas-ahmed-0b52ab334?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app','https://github.com/Ilyakhudus','ahmedmohammedilyas129@gmail.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (42,'Mohammed Huzaif','Operations Associate Head','execom',NULL,NULL,NULL,'placeholder-arif@example.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (43,'Saad uddin','Operations Associate Head','execom',NULL,NULL,NULL,'placeholder-saifuddin@example.com','Operations',NULL,'2025-26',TRUE);
INSERT INTO csi_team (sno,name,position,role,image_url,linkedin,github,mail,portfolio,gb_position,team_year,is_active) VALUES (44,'Hamoody( Mohammed Ayaan)','Media Associate Head','execom',NULL,NULL,'https://github.com/hamoody08','hxmoody08@gmail.com','Media',NULL,'2025-26',TRUE);

INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 11','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition11.png','/pdfs/edition-11.pdf',0);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 10','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition10.png','/pdfs/edition-10.pdf',1);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 9','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition9.png','/pdfs/edition-9.pdf',2);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 8','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition8.png','/pdfs/edition-8.pdf',3);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 7','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition7.png','/pdfs/edition-7.pdf',4);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 6','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition6.png','/pdfs/edition-6.pdf',5);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 5','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition5.png','/pdfs/edition-5.pdf',6);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 4','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition4.png','/pdfs/edition-4.pdf',7);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 3','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition3.png','/pdfs/edition-3.pdf',8);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 2','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition2.png','/pdfs/edition-2.pdf',9);
INSERT INTO magazines (title,description,cover_url,pdf_url,sort_order) VALUES ('Edition 1','Tech Insights, Student Voices, Future Vision - Where Innovation Meets Imagination','/pdfs/edition1.png','/pdfs/edition-1.pdf',10);

INSERT INTO resources (title,pdf_url,image_url,description,sort_order) VALUES ('Tech Foundations','/pdfs/basic-tech.pdf','/images/basic-img.jpg','Get started with essential tools and workflows - learn VS Code, Git, GitHub, and how to kickstart your own projects from scratch.',0);
INSERT INTO resources (title,pdf_url,image_url,description,sort_order) VALUES ('Web Development','/pdfs/web-dev.pdf','/images/web-dev-img.jpeg','Build stunning websites and apps with HTML, CSS, JS, and modern frameworks.',1);
INSERT INTO resources (title,pdf_url,image_url,description,sort_order) VALUES ('App Development','/pdfs/app-dev.pdf','/images/app-dev-img.jpeg','Create mobile experiences for Android, iOS, and cross-platform apps.',2);
INSERT INTO resources (title,pdf_url,image_url,description,sort_order) VALUES ('AI/ML','/pdfs/aiml.pdf','/images/aiml-img.jpeg','Explore machine learning, neural networks, and smart data solutions.',3);
INSERT INTO resources (title,pdf_url,image_url,description,sort_order) VALUES ('IoT','/pdfs/iot.pdf','/images/iot-img.jpeg','Connect devices, sensors, and the world around you with IoT technologies.',4);
INSERT INTO resources (title,pdf_url,image_url,description,sort_order) VALUES ('Blockchain','/pdfs/blockchain.pdf','/images/block-chain-img.jpeg','Dive into decentralized tech, cryptocurrencies, and smart contracts.',5);
INSERT INTO resources (title,pdf_url,image_url,description,sort_order) VALUES ('Cloud Computing','/pdfs/cloud.pdf','/images/cloud-img.jpeg','Master cloud platforms, deployment, and scalable infrastructure.',6);
-- =====================================================
-- 8. EVENT SEEDS (from the old JSON files)
-- =====================================================
ALTER TABLE events ADD COLUMN IF NOT EXISTS subtitle TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS organizers TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS highlights TEXT[];
ALTER TABLE events ADD COLUMN IF NOT EXISTS contacts JSONB;
ALTER TABLE events ADD COLUMN IF NOT EXISTS time_range TEXT;

INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('Volunteer Appreciation Ceremony','Celebrating Our Heroes','As you all know, CSI and E-Cell successfully organized a Hack Revolution 2025 this November, and it wouldn''t have been possible without the incredible effort and dedication from our volunteers! Join us for a short and sweet ceremony filled with appreciation, gratitude, and of course, good vibes!','/events/past/hackrev.jpg','completed','2025-12-12T14:30:00.000Z',NULL,'Seminar Hall','Ceremony',ARRAY['Team CSI']::TEXT[],ARRAY['Appreciation & Gratitude','Good Vibes','Celebration of contribution']::TEXT[],'[{"name": "Team CSI", "phone": "csi@mjcollege.ac.in"}]'::jsonb,'Afternoon',ARRAY['Volunteer','Appreciation','CSI']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('Dev Showdown','Execom Project Showcase','You are invited to ''Dev Showdown'', a project showcase by our very own Execom members! Come and watch the teams present the exciting projects they have been working on. Discover creative and practical tech solutions, get inspiration for your future projects, and connect with the CSI technical community.','/events/past/devshowdown.jpg','completed','2025-12-06T13:45:00.000Z',NULL,'Lab 4','Showcase',ARRAY['CSI MJCET']::TEXT[],ARRAY['Discover creative and practical tech solutions','Get inspiration for your future projects','Learn new ideas, workflows, and approaches','Connect with the CSI technical community']::TEXT[],NULL,'1:45 PM – 4:00 PM',ARRAY['Project Showcase','Innovation','Tech']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('Antigravity Unlocked','Powered by Gemini','Antigravity is trending. AI is evolving. But only a few actually understand what’s coming next. Are you ready to be one of them? Join us for “Antigravity Unlocked Powered by Gemini”, a hands-on journey into the world of Agentic AI and Google’s revolutionary Antigravity framework.','/events/past/antigravity.jpg','completed','2025-12-05T13:45:00.000Z',NULL,'Student Activity Centre','Workshop',ARRAY['Computer Science and Engineering Department','CSI MJCET']::TEXT[],ARRAY['Discover what Agentic AI truly means','Deep dive into Google Antigravity','Hands-on Mini Challenge','Exciting Google swags & exclusive giveaways for winners!']::TEXT[],'[{"name": "Abdullah", "phone": "77802 27803"}, {"name": "Touseef", "phone": "99895 98636"}]'::jsonb,'1:45 PM – 4:00 PM',ARRAY['AI','Google','Agentic AI','Workshop']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('CSI Community Connect','The Ultimate CSI Community Meetup','Brace yourselves because we’re bringing the ultimate CSI COMMUNITY CONNECT! Insanely fun activities, team bonding like never before, high-energy group challenges, and pure chaos + laughter. Meet the entire CSI fam and start the year with a bang!','/events/past/community.jpg','completed','2025-11-28T13:45:00.000Z',NULL,'Student Activity Center, Block 1','Community',ARRAY['CSI MJCET']::TEXT[],ARRAY['Insanely fun activities','Team bonding like never before','High-energy group challenges','Meet the entire CSI fam']::TEXT[],NULL,'1:45 PM – Onwards',ARRAY['Community','Fun','Networking']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('Prompt Arena','Outsmart. Outcreate. Outprompt.','Think you can outsmart AI? Think you can craft prompts that stand out? This is your chance to prove it in a high-energy competition where creativity meets logic and technology! Gear up for 3 electrifying rounds, from a mind-bending Quiz to an intense Prompt Battle and a thrilling Mystery Round!','/events/past/promptarena.jpg','completed','2025-11-21T13:45:00.000Z',NULL,'Seminar Hall, Block 4','Competition',ARRAY['Computer Science and Engineering Department','CSI MJCET']::TEXT[],ARRAY['3 Electrifying Rounds: Quiz, Prompt Battle, Mystery Round','Team Size: 2–3 members','Registration Fee: Absolutely FREE','Exciting prizes to be won']::TEXT[],'[{"name": "Touseef", "phone": "99895 98636"}, {"name": "Affan", "phone": "91217 95950"}]'::jsonb,'1:45 PM – 4:00 PM',ARRAY['AI','Prompt Engineering','Competition','Creativity']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('Hack Revolution 2025','Biggest Flagship Event | Powered by Aces','Get ready to witness the ultimate tech face-off where innovation meets impact. Brought to you by the ultimate duo CSI x E-Cell MJCET a 15-hour coding marathon designed to challenge your creativity, logic, and problem-solving like never before. Win incredible cash prizes from a massive pool of ₹3,00,000! Winners get direct entry to Smart India Hackathon 2026.','/events/past/hackrev.jpg','completed','2025-11-08T09:00:00.000Z',NULL,'Ghulam Ahmed Hall MJCET','Hackathon',ARRAY['CSI MJCET','E-Cell MJCET','ACES']::TEXT[],ARRAY['4 Competitive Tracks: Smart Ed, Urban Tech, Agri & Open Hardware','₹3,00,000 Cash Prize Pool','Direct entry to SIH 2026 for winners','15-hour coding marathon']::TEXT[],'[{"name": "Abdullah", "phone": "77802 27803"}, {"name": "Rayyan", "phone": "99087 84538"}]'::jsonb,'9:00 AM – Onwards',ARRAY['Hackathon','Innovation','Coding','Smart India Hackathon']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('Terraview 2025: Turning Data into Stories','The Ultimate First Year Showdown | Powered by ACES','Exclusively for First-Years! Step into the world of data visualization and show your mettle! This isn’t just any competition, it’s your chance to turn raw data into jaw-dropping insights. Compete for a ₹30,000 cash prize pool! This is a SOLO event - it’s just you, your data, and your vision.','/events/past/teraview2.jpg','completed','2025-11-08T10:00:00.000Z',NULL,'Seminar Hall, Block 4','Competition',ARRAY['ACES','CSI MJCET','E-Cell MJCET']::TEXT[],ARRAY['Exclusively for First-Years','₹30,000 Cash Prize Pool','SOLO Event','Live Presentation Finals']::TEXT[],'[{"name": "Abdullah Shareef", "phone": "77802 27803"}, {"name": "Rayyan", "phone": "99087 84538"}]'::jsonb,'10:00 AM – 1:00 PM',ARRAY['Data Visualization','Competition','Terraview','First Years']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('Data Analytics using Terraview','Turning Data into Stories','First Years Exclusive! Get ready to explore the world of data with Terraview, the platform that transforms raw numbers into impactful insights. Whether you’re a beginner or a curious innovator, this hands-on session will help you craft dashboards that impress and prepare for Terraview 2025 with a ₹30,000 cash prize pool!','/events/past/terraview.jpg','completed','2025-10-29T13:30:00.000Z',NULL,'CIC Lab Block 2','Workshop',ARRAY['ACES','CSI MJCET','E-Cell MJCET']::TEXT[],ARRAY['Fundamentals of data visualization & analytics','Hands on experience with Terraview','Skills to create impactful data stories','Expert tips to shine in Terraview 2025','Certificate of participation']::TEXT[],'[{"name": "Abdullah Shareef", "phone": "77802 27803"}, {"name": "Rayyan", "phone": "99087 84538"}]'::jsonb,'1:30 PM – 4:00 PM',ARRAY['Data Analytics','Terraview','Visualization']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('VisionVerse','The Official Pre-Hackathon Workshop Series of Hack Revolution','Join us for VisionVerse an immersive workshop introducing you to Computer Vision, where machines learn to see and understand the world like humans. In the age of AI, Computer Vision is everywhere! From robotics to smart apps. Learn the skills that help machines see, think, and act. Fee: ₹50/- (Free for CSI & E-Cell Members!)','/events/past/visionverse.jpg','completed','2025-10-25T09:30:00.000Z',NULL,'CIC Lab, Block 2','Workshop',ARRAY['CSI MJCET','E-Cell MJCET']::TEXT[],ARRAY['Fundamentals of Computer Vision & AI','Image processing and object detection','Build hands-on projects with OpenCV / Python','Important Modules of Mediapipe','Real-world applications and workflows']::TEXT[],'[{"name": "Abdullah", "phone": "77802 27803"}, {"name": "Rayyan", "phone": "99087 84538"}]'::jsonb,'9:30 AM – 4:00 PM',ARRAY['Computer Vision','AI','OpenCV','Python']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('WEBVERSE','The Official Pre-Hackathon Workshop Series Of Hackrevolution','CSI and E-Cell MJCET proudly bring you WEBVERSE 🌐– The Web Development Workshop, the first pre-hackathon session of Hack Revolution. Before the hackathon begins, step into the world of web technologies and learn how to turn your ideas into dynamic, creative, and functional web solutions.','/events/past/webverse.jpg','completed','2024-11-16T10:00:00.000Z','2024-11-16T14:00:00.000Z','Lab 301, MJCET','Workshop',ARRAY['CSI MJCET','E-Cell MJCET']::TEXT[],ARRAY['Get Ready to Build the Web of Tomorrow!','Learn React, Next.js, and TypeScript','Turn ideas into dynamic web solutions']::TEXT[],NULL,NULL,ARRAY['Web Development','React','Workshop']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('SIH Decoded – Hear it from the Winners!','Guidance for Smart India Hackathon','Want to Participate in SIH but need guidance? Hear it from the Winners! In 2024, Two CSI teams from MJCET Won SIH. Now, they’re here to share how they did it. Whether you’re curious about hackathons, planning to participate in SIH, or just want to learn from the winners, this session is for you! Fee: ₹50 (Free for CSI Members).','/events/past/sihdecoded.jpg','completed','2025-09-19T10:30:00.000Z',NULL,'CIC Lab, Block 2','Seminar',ARRAY['CSI MJCET']::TEXT[],ARRAY['Live Interaction with SIH 2024 winners','PS Selection Tips – how to choose the right problem statement','Guide to making a Winning PPT','Journey from PS selection to the finale']::TEXT[],'[{"name": "Touseef Banu", "phone": "99895 98636"}, {"name": "Affan Asif", "phone": "91217 95950"}]'::jsonb,'10:30 AM – 1:00 PM',ARRAY['SIH','Hackathon','Guidance','Success Story']::TEXT[],TRUE);
INSERT INTO events (title,subtitle,description,poster_url,status,event_date,event_end_date,venue,category,organizers,highlights,contacts,time_range,tags,is_active) VALUES ('ADSOPHOS 2026','Unleash the Future','ADSOPHOS 2026 is a vibrant two-day fest where fun, creativity, and culinary delights come together. It''s a space to explore, compete, and enjoy a variety of exciting activities with your friends.

From thrilling challenges, a highly insightful Tech expo, to engaging quizzes, watch teams climb their way to the top and leave their mark. Play, compete, and make your place among the best.','/events/ongoing/adsophos.jpeg','ongoing','2026-04-09T09:00:00.000Z','2026-04-10T18:00:00.000Z','MJCET Campus','Technical Fest',ARRAY['CSI MJCET','MJCET']::TEXT[],ARRAY['Two-day Vibrant Fest','Thrilling Challenges & Quizzes','Insightful Tech Expo','Culinary Delights & Fun Activities']::TEXT[],'[{"name": "Team CSI", "phone": "csi@mjcollege.ac.in"}]'::jsonb,'9:00 AM – Onwards',ARRAY['AdSophos','Tech Fest','Innovation','MJCET']::TEXT[],TRUE);
